#include <errno.h>

const char *errno_str(int error);
const char *errno_str(int error) {
  switch (error) {
  case EPERM:
    return EPERM_STR;
  case ENOENT:
    return ENOENT_STR;
  case ESRCH:
    return ESRCH_STR;
  case EINTR:
    return EINTR_STR;
  case EIO:
    return EIO_STR;
  case ENXIO:
    return ENXIO_STR;
  case E2BIG:
    return E2BIG_STR;
  case ENOEXEC:
    return ENOEXEC_STR;
  case EBADF:
    return EBADF_STR;
  case ECHILD:
    return ECHILD_STR;
  case EAGAIN:
    return EAGAIN_STR;
  case ENOMEM:
    return ENOMEM_STR;
  case EACCES:
    return EACCES_STR;
  case EFAULT:
    return EFAULT_STR;
  case ENOTBLK:
    return ENOTBLK_STR;
  case EBUSY:
    return EBUSY_STR;
  case EEXIST:
    return EEXIST_STR;
  case EXDEV:
    return EXDEV_STR;
  case ENODEV:
    return ENODEV_STR;
  case ENOTDIR:
    return ENOTDIR_STR;
  case EISDIR:
    return EISDIR_STR;
  case EINVAL:
    return EINVAL_STR;
  case ENFILE:
    return ENFILE_STR;
  case EMFILE:
    return EMFILE_STR;
  case ENOTTY:
    return ENOTTY_STR;
  case ETXTBSY:
    return ETXTBSY_STR;
  case EFBIG:
    return EFBIG_STR;
  case ENOSPC:
    return ENOSPC_STR;
  case ESPIPE:
    return ESPIPE_STR;
  case EROFS:
    return EROFS_STR;
  case EMLINK:
    return EMLINK_STR;
  case EPIPE:
    return EPIPE_STR;
  case EDOM:
    return EDOM_STR;
  case ERANGE:
    return ERANGE_STR;
  case EDEADLK:
    return EDEADLK_STR;
  case ENAMETOOLONG:
    return ENAMETOOLONG_STR;
  case ENOLCK:
    return ENOLCK_STR;
  case ENOSYS:
    return ENOSYS_STR;
  case ENOTEMPTY:
    return ENOTEMPTY_STR;
  case ELOOP:
    return ELOOP_STR;
  case ENOMSG:
    return ENOMSG_STR;
  case EIDRM:
    return EIDRM_STR;
  case ECHRNG:
    return ECHRNG_STR;
  case EL2NSYNC:
    return EL2NSYNC_STR;
  case EL3HLT:
    return EL3HLT_STR;
  case EL3RST:
    return EL3RST_STR;
  case ELNRNG:
    return ELNRNG_STR;
  case EUNATCH:
    return EUNATCH_STR;
  case ENOCSI:
    return ENOCSI_STR;
  case EL2HLT:
    return EL2HLT_STR;
  case EBADE:
    return EBADE_STR;
  case EBADR:
    return EBADR_STR;
  case EXFULL:
    return EXFULL_STR;
  case ENOANO:
    return ENOANO_STR;
  case EBADRQC:
    return EBADRQC_STR;
  case EBADSLT:
    return EBADSLT_STR;
  case EBFONT:
    return EBFONT_STR;
  case ENOSTR:
    return ENOSTR_STR;
  case ENODATA:
    return ENODATA_STR;
  case ETIME:
    return ETIME_STR;
  case ENOSR:
    return ENOSR_STR;
  case ENONET:
    return ENONET_STR;
  case ENOPKG:
    return ENOPKG_STR;
  case EREMOTE:
    return EREMOTE_STR;
  case ENOLINK:
    return ENOLINK_STR;
  case EADV:
    return EADV_STR;
  case ESRMNT:
    return ESRMNT_STR;
  case ECOMM:
    return ECOMM_STR;
  case EPROTO:
    return EPROTO_STR;
  case EMULTIHOP:
    return EMULTIHOP_STR;
  case EDOTDOT:
    return EDOTDOT_STR;
  case EBADMSG:
    return EBADMSG_STR;
  case EOVERFLOW:
    return EOVERFLOW_STR;
  case ENOTUNIQ:
    return ENOTUNIQ_STR;
  case EBADFD:
    return EBADFD_STR;
  case EREMCHG:
    return EREMCHG_STR;
  case ELIBACC:
    return ELIBACC_STR;
  case ELIBBAD:
    return ELIBBAD_STR;
  case ELIBSCN:
    return ELIBSCN_STR;
  case ELIBMAX:
    return ELIBMAX_STR;
  case ELIBEXEC:
    return ELIBEXEC_STR;
  case EILSEQ:
    return EILSEQ_STR;
  case ERESTART:
    return ERESTART_STR;
  case ESTRPIPE:
    return ESTRPIPE_STR;
  case EUSERS:
    return EUSERS_STR;
  case ENOTSOCK:
    return ENOTSOCK_STR;
  case EDESTADDRREQ:
    return EDESTADDRREQ_STR;
  case EMSGSIZE:
    return EMSGSIZE_STR;
  case EPROTOTYPE:
    return EPROTOTYPE_STR;
  case ENOPROTOOPT:
    return ENOPROTOOPT_STR;
  case EPROTONOSUPPORT:
    return EPROTONOSUPPORT_STR;
  case ESOCKTNOSUPPORT:
    return ESOCKTNOSUPPORT_STR;
  case EOPNOTSUPP:
    return EOPNOTSUPP_STR;
  case EPFNOSUPPORT:
    return EPFNOSUPPORT_STR;
  case EAFNOSUPPORT:
    return EAFNOSUPPORT_STR;
  case EADDRINUSE:
    return EADDRINUSE_STR;
  case EADDRNOTAVAIL:
    return EADDRNOTAVAIL_STR;
  case ENETDOWN:
    return ENETDOWN_STR;
  case ENETUNREACH:
    return ENETUNREACH_STR;
  case ENETRESET:
    return ENETRESET_STR;
  case ECONNABORTED:
    return ECONNABORTED_STR;
  case ECONNRESET:
    return ECONNRESET_STR;
  case ENOBUFS:
    return ENOBUFS_STR;
  case EISCONN:
    return EISCONN_STR;
  case ENOTCONN:
    return ENOTCONN_STR;
  case ESHUTDOWN:
    return ESHUTDOWN_STR;
  case ETOOMANYREFS:
    return ETOOMANYREFS_STR;
  case ETIMEDOUT:
    return ETIMEDOUT_STR;
  case ECONNREFUSED:
    return ECONNREFUSED_STR;
  case EHOSTDOWN:
    return EHOSTDOWN_STR;
  case EHOSTUNREACH:
    return EHOSTUNREACH_STR;
  case EALREADY:
    return EALREADY_STR;
  case EINPROGRESS:
    return EINPROGRESS_STR;
  case ESTALE:
    return ESTALE_STR;
  case EUCLEAN:
    return EUCLEAN_STR;
  case ENOTNAM:
    return ENOTNAM_STR;
  case ENAVAIL:
    return ENAVAIL_STR;
  case EISNAM:
    return EISNAM_STR;
  case EREMOTEIO:
    return EREMOTEIO_STR;
  case EDQUOT:
    return EDQUOT_STR;
  case ENOMEDIUM:
    return ENOMEDIUM_STR;
  case EMEDIUMTYPE:
    return EMEDIUMTYPE_STR;
  default:
    return "Unknown error";
  }
}
